### ISSUE TITLE
change import path in generated .ts files

### ISSUE THREAD

**Issue by ZeeD** [piotr-oles/as-proto#15]
Hi.
according to https://discord.com/channels/721472913886281818/721472913886281821/1002570366016819250 with as 2.0 the import of the as dependencies need to point explicitly to the assembly folder.
Unfortunately it seems to me that the .ts files generated by as-proto-gen starts with `import { Writer, Reader } from "as-proto";` while now they need `import { Writer, Reader } from "as-proto/assembly";`.

I don't know if there is some way to autodetect the as version and/or some parameter to pass to protoc, but now it seems the tool is not fully compatible with as 2.0

**Comment by dvoytenko** [comment]
Seeing the same error as well.

**Comment by piotr-oles** [comment]
Fixed in #26

**Comment by dvoytenko** [comment]
Thank you!
