### ISSUE TITLE
cannot export class

### ISSUE THREAD

**Issue by ZeeD** [piotr-oles/as-proto#17]
It seems that the class generated by as-proto-gen is not compatible with as 2.0:

```
> asc assembly/index.ts --target debug

WARNING AS235: Only variables, functions and enums become WebAssembly module exports.
   :
 3 │ export class Person {
   │              ~~~~~~
   └─ in assembly/proto/person.ts(3,14)

```

using
```
$ npm list       
prova_as@1.0.0 /Users/a206719281/eclipse-workspace/_prova_as
+-- as-proto-gen@0.2.5
+-- as-proto@0.2.5
+-- assemblyscript@0.20.16
`-- serve@14.0.1
```

**Comment by piotr-oles** [comment]
It looks like a warning - not an error. You can't use generated classes directly from JavaScript environment, but you can use it in other AssemblyScript files.
You can enable `--as_opt=gen-helper-methods` flag to generate helper functions that you can use directly from the JavaScript :) (it would be `encodePerson()` and `decodePerson()` functions in this case)
