### ISSUE TITLE
as-proto should export JS files, and not TS

### ISSUE THREAD

**Issue by EWhite613** [piotr-oles/as-proto#53]
Right now https://github.com/piotr-oles/as-proto/blob/main/packages/as-proto/package.json#L4 uses the `index.ts` as a main.  When should probably be a js file

Meaning consumer needs to compile it, and if using Typescript already may have some issues working in that package's own config

**Comment by rellfy** [comment]
This is an AssemblyScript project. The main file should remain as `ts`, which is actually AssemblyScript and not TypeScript.
