### ISSUE TITLE
`null` return values do not follow proto3 spec

### ISSUE THREAD

**Issue by mvandeberg** [piotr-oles/as-proto#7]
`string` and `bytes` proto3 types do not have correct default value semantics.

According to the [Protobuf Documentation](https://developers.google.com/protocol-buffers/docs/proto3#default), `string` and `bytes` types should be default initialized to an empty string and empty byte array, respectively.

For reference, my proto type:

``` proto3
message event_arguments {
   string name = 1;
   bytes data = 2;
   repeated bytes impacted = 3;
}
```

Generates a class with the following fields and constructor:

``` ts
  name: string | null;
  data: Uint8Array | null;
  impacted: Array<Uint8Array>;

  constructor(
    name: string | null = null,
    data: Uint8Array | null = null,
    impacted: Array<Uint8Array> = []
  ) {
    this.name = name;
    this.data = data;
    this.impacted = impacted;
  }
  ```
  
I believe removing the `| null` from `Uint8Array` and `string` generated fields would fix the problem.
Note: `impacted` appears to be correct and `| null` should probably remain on all fields marked `optional`.

**Comment by piotr-oles** [comment]
Thanks for the report. Would you be interested in making a PR? :)
